<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_AppelEtage" Id="{5623fef1-f5ac-4bc7-a33a-1a92002ecfee}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_AppelEtage

VAR_INPUT
	
END_VAR

VAR_OUTPUT
	
END_VAR

VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_AppelEtage">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>